[gcloud]
disabled = true

[git_commit]
tag_disabled = false

[vagrant]
disabled = true

[hostname]
ssh_only = false

[status]
disabled = false
symbol = "âœ– "

[character]
success_symbol = '[\$](bold blue)'
error_symbol = '[\$](bold red)'

[directory]
truncation_length = 10

#
# for screencasts, comment the battery.display section
#
[[battery.display]]
threshold = 15
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 50
discharging_symbol = "âš ï¸ "

[[battery.display]]
threshold = 80
style = 'blue'

[[battery.display]]
threshold = 90
style = 'green'

# #
# # for screencasts, uncomment below here
# #
# [git_status]
# disabled = true

# [git_branch]
# disabled = true

# [ruby]
# disabled = true
